apply plugin: 'com.android.application'

android {
    compileSdk 37

    Properties properties = new Properties()
    if (project.rootProject.file('local.properties').exists()) {
        properties.load(project.rootProject.file('local.properties').newDataInputStream())
    }

    signingConfigs {
        release {
            storeFile file("../keystore/windmill_weather_upload.jks")
            storePassword properties.getProperty('keystore.password')
            keyAlias properties.getProperty('keystore.alias')
            keyPassword properties.getProperty('keystore.password')
        }
    }

    defaultConfig {
        applicationId "com.windmill.dam2.windmillweather"
        minSdkVersion  28
        targetSdkVersion 37
        versionCode 2
        versionName "1.2"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    namespace 'com.windmill.dam2.windmillweather'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint {
        baseline file('AndroidManifest.xml')
        disable 'GoogleAppIndexingWarning'
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.core:core-splashscreen:1.0.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation 'com.google.android.material:material:1.11.0'

    //Agreagamos las librerias del RSS Reader y JSON
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'com.google.code.gson:gson:2.10.1'

    //Agragamos las librerias para poder meter un GIF
    implementation 'com.felipecsl:gifimageview:2.1.0'
    implementation 'commons-io:commons-io:2.7'
    implementation 'org.jetbrains:annotations:24.0.1'


}
